### ISSUE TITLE
Sonde supplémentaire

### ISSUE THREAD

**Issue by Grubuntu** [Jetblack31/EcoPV#2]
Une sonde supplémentaire pour pouvoir suivre aussi la production solaire, ça permettrait de centraliser le suivi de production, consommation et routage sur un seul arduino.

**Comment by Jetblack31** [comment]
Une entrée pour impulsions d'un compteur de production est prévue pour bientôt.
Par contre ce n'est pas possible d'ajouter une pince ampéremétrique, ça ralentirait l'arduino...
